Elementy HTML zostały wyłączone ze wględów bezpieczeństwa!!!! <br>
Przesyłanie zdjęć i gifów zostanie opracowane później. <br>
Dziękuję za zrozumienie. <br>
Poza tym wszystko działa i posiada otwarty endpoint (jak będziecie go nadużywać zamknię go 😉) <br>
Możecie tutaj pisać wszystko, ale proszę nienadużywać przeklęstw.<br>
Stay Safe! <br>
TexturedPolak, <br>
Główny Developer <br>
Ps. Dziękuję użytkownikowi discorda "szumiaczek" za pomoc designowaniu menu logowania i rejestracji <br>
&lt;Textured&gt; teraz<br>&lt;Textured&gt; jej<br>&lt;Textured&gt; jej<br>&lt;Textured&gt; <br>&lt;Textured&gt; eje<br>&lt;Textured&gt; je<br>&lt;Textured&gt; jejejejje<br>&lt;Textured&gt; jejeje<br>&lt;Textured&gt; je<br>&lt;Textured&gt; je<br>&lt;Textured&gt; dzmeu<br>&lt;Textured&gt; e<br>&lt;Textured&gt; p<br>&lt;Textured&gt; teraz<br>&lt;Textured&gt; tak<br>&lt;Textured&gt; nareszcie<br>&lt;Textured&gt; templaty są dziwne lekko<br>&lt;Textured&gt; tylko czemu<br>&lt;Textured&gt; d<br>&lt;Textured&gt; siemanko<br>&lt;Textured&gt; helok<br>&lt;Textured&gt; jol<br>&lt;Textured&gt; e<br>&lt;Textured&gt; tak<br>&lt;Textured&gt; t<br>&lt;Textured&gt; t<br>&lt;Textured&gt; g<br>&lt;Textured&gt; d<br>&lt;Textured&gt; jol<br>&lt;Textured&gt; tak<br>&lt;Textured&gt; cos<br>&lt;Textured&gt; tak<br>&lt;Textured&gt; jej<br>&lt;Textured&gt; nie widać tego imo<br>&lt;Textured&gt; troszkę<br>&lt;Textured&gt; optymalizacja wjedzie będzie git<br>&lt;Textured&gt; 1<br>&lt;Textured&gt; 2<br>&lt;Textured&gt; 3<br>&lt;TexturedPolak&gt; ;)<br>&lt;TexturedPolak&gt; jol<br>&lt;TexturedPolak&gt; yes<br>&lt;TexturedPolak&gt; siemanko<br><span style="color: #79b6c9;">&lt;bottle.SimpleTemplate object at 0x7f9b74e49250&gt;</span>?<br><span style="color: #79b6c9;">Textured</span>?<br><span style="color: #79b6c9;">&lt;Textured&gt;</span> tak<br><span style="color: #79b6c9;">&lt;Textured&gt;</span> ?<br>